INCLUDE(FindPackageHandleStandardArgs)
INCLUDE(HandleLibraryTypes)

SET(MVBF_IncludeSearchPaths
  /usr/include/mvBlueFox/
  /usr/local/include/mvBlueFox/
  /opt/local/include/mvBlueFox/
  ${MVBF_PKGCONF_INCLUDE_DIRS}
)

SET(MVBF_LibrarySearchPaths
  /usr/lib/mvBlueFox/x86_64/
  /usr/local/lib/mvBlueFox/x86_64/
  /opt/local/lib/mvBlueFox/x86_64/
)

FIND_PATH(MVBF_INCLUDE_DIR
  NAMES mvIMPACT_CPP/mvIMPACT_acquire.h
  PATHS ${MVBF_IncludeSearchPaths}
)
FIND_LIBRARY(MVBF_MAIN_LIBRARY_OPTIMIZED
  NAMES mvBlueFOX
  PATHS ${MVBF_LibrarySearchPaths}
)
FIND_LIBRARY(MVBF_DEVMGR_LIBRARY_OPTIMIZED
  NAMES mvDeviceManager
  PATHS ${MVBF_LibrarySearchPaths}
)
FIND_LIBRARY(MVBF_PROPHNDL_LIBRARY_OPTIMIZED
  NAMES mvPropHandling
  PATHS ${MVBF_LibrarySearchPaths}
)

# Handle the REQUIRED argument and set the <UPPERCASED_NAME>_FOUND variable
# The package is found if all variables listed are TRUE
FIND_PACKAGE_HANDLE_STANDARD_ARGS(MVBF_MAIN "Could NOT find mvBlueFox library"
  MVBF_MAIN_LIBRARY_OPTIMIZED
  MVBF_INCLUDE_DIR
)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(MVBF_DEVMGR "Could NOT find mvBlueFox (DeviceManager) library"
  MVBF_DEVMGR_LIBRARY_OPTIMIZED
  MVBF_INCLUDE_DIR
)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(MVBF_PROPHNDL "Could NOT find mvBlueFox (PropHandling) library"
  MVBF_PROPHNDL_LIBRARY_OPTIMIZED
  MVBF_INCLUDE_DIR
)

set(MVBF_LIBRARIES)
list(APPEND MVBF_LIBRARIES ${MVBF_MAIN_LIBRARY_OPTIMIZED})
list(APPEND MVBF_LIBRARIES ${MVBF_DEVMGR_LIBRARY_OPTIMIZED})
list(APPEND MVBF_LIBRARIES ${MVBF_PROPHNDL_LIBRARY_OPTIMIZED})

find_package_handle_standard_args(MVBF DEFAULT_MSG MVBF_LIBRARIES MVBF_INCLUDE_DIR)
mark_as_advanced(MVBF_LIBRARIES MVBF_INCLUDE_DIR)

MARK_AS_ADVANCED(
  MVBF_INCLUDE_DIR
  MVBF_LIBRARY_OPTIMIZED
)
MARK_AS_ADVANCED(
  MVBF_INCLUDE_DIR
  MVBF_DEVMGR_LIBRARY_OPTIMIZED
)
MARK_AS_ADVANCED(
  MVBF_INCLUDE_DIR
  MVBF_PROPHNDL_LIBRARY_OPTIMIZED
)
