INCLUDE(FindPackageHandleStandardArgs)
INCLUDE(HandleLibraryTypes)

SET(OpenCV_IncludeSearchPaths
  /usr/include/
  /usr/include/opencv-2.3.1/
  /usr/local/include/
  /opt/local/include/
)

SET(OpenCV_LibrarySearchPaths
  /usr/lib/
  /usr/local/lib/
  /opt/local/lib/
)

FIND_PATH(OPENCV_IMGPROC_INCLUDE_DIR opencv2/opencv.hpp
  PATHS ${OpenCV_IncludeSearchPaths}
)
FIND_LIBRARY(OPENCV_IMGPROC_LIBRARY_OPTIMIZED
  NAMES opencv_imgproc
  PATHS ${OpenCV_LibrarySearchPaths}
)

FIND_PATH(OPENCV_CALIB3D_INCLUDE_DIR opencv2/opencv.hpp
  PATHS ${OpenCV_IncludeSearchPaths}
)
FIND_LIBRARY(OPENCV_CALIB3D_LIBRARY_OPTIMIZED
  NAMES opencv_calib3d
  PATHS ${OpenCV_LibrarySearchPaths}
)

FIND_PATH(OPENCV_FEATURES2D_INCLUDE_DIR opencv2/opencv.hpp
  PATHS ${OpenCV_IncludeSearchPaths}
)
FIND_LIBRARY(OPENCV_FEATURES2D_LIBRARY_OPTIMIZED
  NAMES opencv_features2d
  PATHS ${OpenCV_LibrarySearchPaths}
)

FIND_PATH(OPENCV_FLANN_INCLUDE_DIR opencv2/opencv.hpp
  PATHS ${OpenCV_IncludeSearchPaths}
)
FIND_LIBRARY(OPENCV_FLANN_LIBRARY_OPTIMIZED
  NAMES opencv_flann
  PATHS ${OpenCV_LibrarySearchPaths}
)

FIND_PATH(OPENCV_OBJDETECT_INCLUDE_DIR opencv2/opencv.hpp
  PATHS ${OpenCV_IncludeSearchPaths}
)
FIND_LIBRARY(OPENCV_OBJDETECT_LIBRARY_OPTIMIZED
  NAMES opencv_objdetect
  PATHS ${OpenCV_LibrarySearchPaths}
)

FIND_PATH(OPENCV_VIDEO_INCLUDE_DIR opencv2/opencv.hpp
  PATHS ${OpenCV_IncludeSearchPaths}
)
FIND_LIBRARY(OPENCV_VIDEO_LIBRARY_OPTIMIZED
  NAMES opencv_video
  PATHS ${OpenCV_LibrarySearchPaths}
)

FIND_PATH(OPENCV_LEGACY_INCLUDE_DIR opencv2/opencv.hpp
  PATHS ${OpenCV_IncludeSearchPaths}
)
FIND_LIBRARY(OPENCV_LEGACY_LIBRARY_OPTIMIZED
  NAMES opencv_legacy
  PATHS ${OpenCV_LibrarySearchPaths}
)

FIND_PATH(OPENCV_CONTRIB_INCLUDE_DIR opencv2/opencv.hpp
  PATHS ${OpenCV_IncludeSearchPaths}
)
FIND_LIBRARY(OPENCV_CONTRIB_LIBRARY_OPTIMIZED
  NAMES opencv_contrib
  PATHS ${OpenCV_LibrarySearchPaths}
)

FIND_PATH(OPENCV_CORE_INCLUDE_DIR opencv2/opencv.hpp
  PATHS ${OpenCV_IncludeSearchPaths}
)
FIND_LIBRARY(OPENCV_CORE_LIBRARY_OPTIMIZED
  NAMES opencv_core
  PATHS ${OpenCV_LibrarySearchPaths}
)

FIND_PATH(OPENCV_ML_INCLUDE_DIR opencv2/opencv.hpp
  PATHS ${OpenCV_IncludeSearchPaths}
)
FIND_LIBRARY(OPENCV_ML_LIBRARY_OPTIMIZED
  NAMES opencv_ml
  PATHS ${OpenCV_LibrarySearchPaths}
)

FIND_PATH(OPENCV_HIGHGUI_INCLUDE_DIR opencv2/opencv.hpp
  PATHS ${OpenCV_IncludeSearchPaths}
)
FIND_LIBRARY(OPENCV_HIGHGUI_LIBRARY_OPTIMIZED
  NAMES opencv_highgui
  PATHS ${OpenCV_LibrarySearchPaths}
)

# Handle the REQUIRED argument and set the <UPPERCASED_NAME>_FOUND variable
FIND_PACKAGE_HANDLE_STANDARD_ARGS(OpenCV "Could NOT find opencv_imgproc (OpenCV)"
  OPENCV_IMGPROC_LIBRARY_OPTIMIZED
  OPENCV_IMGPROC_INCLUDE_DIR
)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(OpenCV "Could NOT find opencv_calib3d (OpenCV)"
  OPENCV_CALIB3D_LIBRARY_OPTIMIZED
  OPENCV_CALIB3D_INCLUDE_DIR
)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(OpenCV "Could NOT find opencv_legacy (OpenCV)"
  OPENCV_LEGACY_LIBRARY_OPTIMIZED
  OPENCV_LEGACY_INCLUDE_DIR
)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(OpenCV "Could NOT find opencv_contrib (OpenCV)"
  OPENCV_CONTRIB_LIBRARY_OPTIMIZED
  OPENCV_CONTRIB_INCLUDE_DIR
)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(OpenCV "Could NOT find opencv_core (OpenCV)"
  OPENCV_CORE_LIBRARY_OPTIMIZED
  OPENCV_CORE_INCLUDE_DIR
)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(OpenCV "Could NOT find opencv_highgui (OpenCV)"
  OPENCV_HIGHGUI_LIBRARY_OPTIMIZED
  OPENCV_HIGHGUI_INCLUDE_DIR
)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(OpenCV "Could NOT find opencv_ml (OpenCV)"
  OPENCV_ML_LIBRARY_OPTIMIZED
  OPENCV_ML_INCLUDE_DIR
)

# Collect optimized and debug libraries
HANDLE_LIBRARY_TYPES(OPENCV_HIGHGUI_LIBRARY_OPTIMIZED)
HANDLE_LIBRARY_TYPES(OPENCV_CORE_LIBRARY_OPTIMIZED)
HANDLE_LIBRARY_TYPES(OPENCV_CONTRIB_LIBRARY)
HANDLE_LIBRARY_TYPES(OPENCV_LEGACY_LIBRARY)
HANDLE_LIBRARY_TYPES(OPENCV_VIDEO_LIBRARY)
HANDLE_LIBRARY_TYPES(OPENCV_OBJDETECT_LIBRARY)
HANDLE_LIBRARY_TYPES(OPENCV_ML_LIBRARY)
HANDLE_LIBRARY_TYPES(OPENCV_IMGPROC_LIBRARY)
HANDLE_LIBRARY_TYPES(OPENCV_FEATURES2D_LIBRARY)
HANDLE_LIBRARY_TYPES(OPENCV_FLANN_LIBRARY)

MARK_AS_ADVANCED(
  OPENCV_HIGHGUI_INCLUDE_DIR
  OPENCV_HIGHGUI_LIBRARY_OPTIMIZED

  OPENCV_CORE_LIBRARY_INCLUDE_DIR
  OPENCV_CORE_LIBRARY_LIBRARY_OPTIMIZED
  
  OPENCV_OPENCV_CONTRIB_INCLUDE_DIR
  OPENCV_OPENCV_CONTRIB_LIBRARY_OPTIMIZED

  OPENCV_OPENCV_LEGACY_LIBRARY_INCLUDE_DIR
  OPENCV_OPENCV_LEGACY_LIBRARY_LIBRARY_OPTIMIZED
  
  OPENCV_OPENCV_VIDEO_INCLUDE_DIR
  OPENCV_OPENCV_VIDEO_LIBRARY_OPTIMIZED
  
  OPENCV_OPENCV_OBJDETECT_INCLUDE_DIR
  OPENCV_OPENCV_OBJDETECT_LIBRARY_OPTIMIZED
  
  OPENCV_OPENCV_ML_INCLUDE_DIR
  OPENCV_OPENCV_ML_LIBRARY_OPTIMIZED
  
  OPENCV_OPENCV_IMGPROC_INCLUDE_DIR
  OPENCV_OPENCV_IMGPROC_LIBRARY_OPTIMIZED
  
  OPENCV_OPENCV_FEATURES2D_INCLUDE_DIR
  OPENCV_OPENCV_FEATURES2D_LIBRARY_OPTIMIZED
  
  OPENCV_OPENCV_FLANN_INCLUDE_DIR
  OPENCV_OPENCV_FLANN_LIBRARY_OPTIMIZED
)
